// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxngbscjdugksftndvgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4bmdic2NqZHVna3NmdG5kdmdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3ODc0NzUsImV4cCI6MjA2NDM2MzQ3NX0.t_AS0_Ganjhj_Q1b22lCpBbibbXQPjaCG1Tt8vUmoaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);